Completely rewrote backup,     now handles full/incremental backups, excluded files/directories, etc.

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -1,46 +1,82 @@
 #!/bin/sh
 
-# JIM: change to take an argument for full vs incremental
-#  change both full and incremental to use find command to get list of
-#  files to back.
-# Incremental should use date of last full backup to get newer files.
-# Also figure out if compression is working!
+# backup script to:
+#    tar up files in specific directories
+#    exclude certain directories/files
+# and put the tar file somewhere - intended to be on some other disk somewhere.
+# Does full and incremental backups
 
-filename=`date "+%Y.%m.%d-%H.%M"`
-target=/Volumes/jak/MacBackups
-last_incremental=$target/`cat $target/last_incremental`
-echo $last_incremental
+targetDir=/Volumes/jak/MacBackups	# where backups should be stored
+#targetDir=$HOME				# where backups should be stored
+dateString=`date "+%Y.%m.%d-%H.%M"`
+excludeFile="$HOME/.backupExcludes"	# file of tar exclude patterns
+lastFullBackupFile=$targetDir/LastFullBackupDate	# touch file of last
+							# full backup date
+backupType="full"		# default backup type
 
-#archive=$target/full.${filename}.tar	# for full backup
-archive=$target/inc.${filename}.tar	# for incremental backup
+if [ "$1" == "--help" -o "$#" -gt 1 ]; then
+    echo "$0 {full|incremental}"
+    echo "puts backups in $targetDir"
+    exit 5
+fi
+if [ $# -eq 1 ]; then
+    backupType=$1
+fi
 
-echo backing up to:  $archive
-cd		# to home directory
+# list of directories/files to backup
+# all relative to home directory
+toBackUp=( \
+   ./bin          \
+   ./Desktop      \
+   ./other        \
+   ./Documents    \
+   ./lib          \
+   ./manager      \
+   ./oboedit_config\
+   ./Signatures   \
+   ./work         \
+   ./.bash*	   \
+   ./.exrc	   \
+   ./.vimrc	   \
+   ./.gitconfig   \
+)
 
-# for incrementals
-find -f		\
-./bin		\
-./Desktop	\
-./other		\
-./Documents	\
-./lib		\
-./manager	\
-./personal	\
-./oboedit_config \
-./Signatures	\
-./work		\
--not -path "*/Microsoft User Data/*" \
--not -path "*/Statsitics_I/Videos/*" \
--type f -newer  $last_incremental  > /tmp/jakfilelist
+# list of directories/files to exclude from backup
+# only need to exclude things if they are in the directories above
+cat - > $excludeFile <<-EndOfExcludes
+	*/Statistics_I/Videos/
+	*/venv/
+	*/Stale/
+	*/.git/
+	*/About?Stacks*
+	*/Microsoft?User?Data*
+EndOfExcludes
 
-tar cvf ${archive} -z -T /tmp/jakfilelist
-rm -f /tmp/jakfilelist
-echo ${archive} > $last_incremental	# remember the latest incremental file
+if [ "$backupType" == "full" ]; then
+    archiveName=$targetDir/full.${dateString}.tar.bzip2
+    newer=""				# no tar "newer" option
+    touch $lastFullBackupFile 		# remember full backup date/time
+
+elif [ "$backupType" == incremental ]; then
+    if [ ! -f $lastFullBackupFile ]; then
+	echo "$0:   $lastFullBackupFile does not exist."
+	echo "$0:   Please do a full backup instead of an incremental"
+	exit 5
+    fi
+    archiveName=$targetDir/incr.${dateString}.tar.bzip2
+    newer="--newer-mtime-than $lastFullBackupFile"
+    echo "$0:   backing up files since" `stat -f "%t%Sm" $lastFullBackupFile`
+else
+    echo "$0:   invalid backup type: $backupType"
+    exit 5
+fi
+
+tarCmd="tar -cvyf $archiveName $newer -X $excludeFile ${toBackUp[*]}"
+
+echo "$tarCmd"
+
+cd		# run from home directory
+$tarCmd
+rm -f $excludeFile
 
 exit 0
-# full backup
-tar cvf ${archive} -z  \
---exclude "Documents/Microsoft User Data/" \
---exclude "Statistics_I/Videos/" \
-./bin ./Desktop ./dev ./Documents ./lib ./manager ./personal ./oboedit_config ./Signatures ./work
-
